apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-nodejs-app.fullname" . }}
  labels:
    {{- include "demo-nodejs-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-nodejs-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "demo-nodejs-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecretsName | default "nexus-credentials" }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 | default "runAsUser: 1001\nfsGroup: 1001" }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
             {{- toYaml .Values.securityContext | nindent 12 | default "allowPrivilegeEscalation: false\nrunAsNonRoot: true\ncapabilities:\n  drop:\n  - ALL" }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort | default 3000 }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
