name: "IaC Scan"

on:
  workflow_call:
    inputs:
      working_directory:
        type: string
        required: false
        default: "."
    outputs:
      iac_report:
        value: "iac-report.sarif"

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "IaC scan placeholder"
