name: "SAST Runner"

on:
  workflow_call:
    inputs:
      languages:
        type: string
        required: false
    outputs:
      sarif_file:
        value: "sast-output.sarif"

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SAST placeholder"
