name: "SCA Runner"

on:
  workflow_call:
    inputs:
      sbom_path:
        type: string
        required: true
    outputs:
      sca_report:
        value: "sca-report.json"

jobs:
  sca:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SCA placeholder"
