name: "Maven CI"

on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        type: string
        default: "."
      config_path:
        required: false
        type: string
        default: "devx.config.yml"
      build_tag:
        required: false
        type: string
    secrets: {}

jobs:
  maven-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Maven CI workflow will be implemented here."
